version: "3.6"

services:
  blitzerbot:
    build:
      context: .
      network: host
    image: ghcr.io/worty/blitzerbot:latest
    container_name: blitzerbot
    restart: always
    network_mode: host
    tmpfs:
      - /tmp
    environment:
      - TZ=Europe/Berlin
      - TWITTER_TARGET_ACCOUNT=AAA
      - TELEGRAM_TOKEN=AAA
      - TELEGRAM_CHAT_ID=@AAA
